version: '3'


services:
    web_test:
      build:
        context: .
        dockerfile: Dockerfile.dev 
      ports:
        - "8585:80"
    sql:
      image: mariadb
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example